name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
        working-directory: frontend/
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
        working-directory: frontend/
      - name: Run Playwright tests
        run: export DEBUG=testcontainers* && pnpm run tc-e2e
        working-directory: frontend/
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
