name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
        with:
          projectBaseDir: frontend/
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
        with:
          projectBaseDir: frontend/
      - name: Run Playwright tests
        run: pnpm exec playwright test
        with:
          projectBaseDir: frontend/
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
